Purging of Templates flag, IPMI Interface support, PSK Authentication
voxpupuli/puppet-zabbix pull request #700
Opened 2020-08-05 06:47 UTC by cbergmann

#### Pull Request (PR) description
This Pull request implements three Features:

1. It adds a new parameter `purge_templates` to zabbix_agent that controls if additional templates configured in the server for the zabbix_host resource should be deleted.
2. it implements psk authentication for zabbix_host resources
3. it fixes a problem with zabbix_host resources with only IPMI interfaces 

I found no easy way to split these commits into three PRs. If you know how to do this I would highly appreciate this.

#### This Pull Request (PR) fixes the following issues

2020-08-25 20:37 UTC, bastelfreak commented on manifests/agent.pp
> +  $tlscertissuer                                  = $zabbix::params::agent_tlscertissuer,
can you add datatypes for those new parameters please?

2020-08-25 20:38 UTC, bastelfreak commented on manifests/agent.pp
> +  Optional[Boolean] $purge_templates              = $zabbix::params::agent_purge_templates,
Optional around a boolean is an anti pattern that we try to avoid. Can't we just default to true or false?

2020-08-25 20:38 UTC, bastelfreak commented on manifests/agent.pp
> +  Optional[Boolean] $purge_templates              = $zabbix::params::agent_purge_templates,
I think this parameter is also missing in the documentation?

2020-08-25 20:41 UTC, bastelfreak commented on manifests/agent.pp
> +  $listen_ip = join($listen_ips,',')
I think those changed lines don't really relate to the rest of this PR? Can you provide it as a dedicated PR?

2020-08-25 20:44 UTC, bastelfreak commented on manifests/agent.pp
> +    $real_tlspskfile = $zabbix::params::default_pskfile_path
what's the benefit of having default_pskfile_path and tlspskfile? can't we just set zabbix::agent::tlspskfile to the value you assigned in params.pp to default_pskfile_path?

2020-08-25 20:48 UTC, bastelfreak commented
thanks for the awesome PR! I left some inline comments. I'm afraid we need to get https://github.com/voxpupuli/puppet-zabbix/pull/699 green somehow first. That will fix most of your CI failures. I'm very familiar with Puppet, but not  that much with Zabbix. If you've any clue with https://github.com/voxpupuli/puppet-zabbix/pull/699 fails please respond there. that would unblock many other PRs as well.

2020-08-26 06:15 UTC, igalic requested changes
i don't understand why this isn't three separate pull requests

github's review UI makes it impossible to review a pull request commit by commit, so packing three such vastly different features and fixes into a single pull request makes review from people who aren't deeply familiar with the code and the server near impossible.

2020-09-11 00:22 UTC, aclarkee reviewed
Testing this in my dev environment, (For PSK support & IPMI) so have added some thoughts/things I came across.

2021-08-11 00:57 UTC, aclarkee commented
FYI @cbergmann as of zabbix 5.4 - PSK values are write only. Current logic triggers a refresh of the PSK values on every run, since they can't be read back to verify. 

Any chance you've fixed that in your environment?

2021-08-13 05:38 UTC, cbergmann commented
> 
> 
> FYI @cbergmann as of zabbix 5.4 - PSK values are write only. Current logic on 5.4.x triggers a refresh of the PSK values on every run, since they can't be read back to verify.
> 
> Any chance you've fixed that in your environment?

Unfortunately I am currently not using this Module. I forwarded this information to my former colleagues and will come back to you if they had found a workaround.

2021-08-13 07:29 UTC, aclarkee commented
> > FYI @cbergmann as of zabbix 5.4 - PSK values are write only. Current logic on 5.4.x triggers a refresh of the PSK values on every run, since they can't be read back to verify.
> > Any chance you've fixed that in your environment?
> 
> Unfortunately I am currently not using this Module. I forwarded this information to my former colleagues and will come back to you if they had found a workaround.

Thanks - I have made a workaround myself, but it's pretty much a bodge - and not really worthy of being merged in..

Would like to see a better fix from someone who better understands ruby/puppet exported resources :)

2022-11-11 03:45 UTC, closed without merging