release 9.0.0
voxpupuli/puppet-zabbix pull request #741
Opened 2021-02-26 21:23 UTC by bastelfreak

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2021-04-27 18:10 UTC, oranenj approved these changes

2021-04-27 18:12 UTC, oranenj requested changes
Actually, maybe drop Ubuntu 16.04 support from this one too before releasing 9.0.0?

2021-04-28 18:56 UTC, bastelfreak commented
given that ubuntu 18 does not yet work (https://github.com/voxpupuli/puppet-zabbix/pull/755) I would like to keep ubuntu 16 for now.

2021-04-28 23:10 UTC, kenyon approved these changes

2021-05-01 12:00 UTC, root-expert commented
Can we maybe merge #735 before releasing? 
Also Zabbix 5.2 is EOL since yesterday

2021-05-07 09:45 UTC, merged