update dependency to fix acceptance test
voxpupuli/puppet-zabbix pull request #924
Opened 2024-03-02 21:49 UTC by Valantin

#### Pull Request (PR) description
Update puppetlabs/postgresql to solve problem with gpg key Update puppetlabs/apache to solve problrm with puppet8 and duplicated parameter

#### This Pull Request (PR) fixes the following issues
Fixes #922

2024-03-02 22:44 UTC, kenyon requested changes
These should be major versions, due to [semantic versioning](https://semver.org/).

2024-03-02 22:44 UTC, kenyon commented on metadata.json
> +      "version_requirement": ">= 6.4.0 < 10.1.0"
```suggestion
      "version_requirement": ">= 6.4.0 < 11.0.0"
```

2024-03-02 22:44 UTC, kenyon commented on metadata.json
> +      "version_requirement": ">= 9.0.0 < 12.1.0"
```suggestion
      "version_requirement": ">= 9.0.0 < 13.0.0"
```

2024-03-03 20:59 UTC, TheMeier approved these changes

2024-03-03 21:28 UTC, kenyon approved these changes

2024-03-03 21:29 UTC, merged