Repository URL change since Zabbix 7.2
voxpupuli/puppet-zabbix pull request #981
Opened 2024-12-14 22:42 UTC by Safranil

#### Pull Request (PR) description

Zabbix 7.2 was published some day ago and the repository base URL changed from
`https://repo.zabbix.com/zabbix/7.0/<os>` to `https://repo.zabbix.com/zabbix/7.2/release/<os>`.

This PR fix the URL for Zabbix 7.2 and newer version.

#### This Pull Request (PR) fixes the following issues

No issue was opened.

2025-01-27 12:40 UTC, Valantin commented
Hi, actually the module test supports only LTS release of zabbix, due to the short release schedule of that standard one.
I suggest you to change the PR to add parameter to support 7.2 without add explicit check for it.

2025-01-27 12:46 UTC, Valantin requested changes
use the variable instead add new complexity for standar release every 6 month

2025-01-27 12:46 UTC, Valantin commented on manifests/database/mysql.pp
> +    if versioncmp($zabbix_version, '7.2') >= 0 {
why not just use $database_schema_path?

2025-01-27 12:46 UTC, Valantin commented on manifests/database/postgresql.pp
> +  } elsif versioncmp($zabbix_version, '7.2') >= 0 {
same as for mysql

2025-01-27 12:46 UTC, Valantin commented on manifests/repo.pp
> +          undef   => versioncmp($zabbix_version, '7.2') ? {
You can specify $repo_location

2025-01-27 12:46 UTC, Valantin commented on manifests/web.pp
> +    $zabbix_ui_dir = versioncmp($zabbix_version, '7.2') ? {
set zabbix_ui_dir as a parameter with the default as /usr/share/zabbix

2025-01-27 12:46 UTC, Valantin commented on spec/classes/database_mysql_spec.rb
> +        path = if Puppet::Util::Package.versioncmp(zabbix_version, '7.2') >= 0
no test for standard release

2025-01-27 12:46 UTC, Valantin commented on spec/classes/database_postgresql_spec.rb
> +        path = if Puppet::Util::Package.versioncmp(zabbix_version, '7.2') >= 0
no test for standard release

2025-01-27 12:46 UTC, Valantin commented on spec/classes/repo_spec.rb
> +
no test for standard release

2025-01-27 12:46 UTC, Valantin commented on spec/support/acceptance/supported_versions.rb
> +  supported_versions = %w[5.0 6.0 7.0 7.2]
remove 7.2 because we only test LTS release

2025-02-20 14:29 UTC, bartjackbakker reviewed
This change is a good preparation for the LTS version 8.0.

2025-02-20 14:29 UTC, bartjackbakker commented on manifests/database/mysql.pp
> +    if versioncmp($zabbix_version, '7.2') >= 0 {
This change is a good preparation for the LTS version 8.0.

2025-02-20 14:29 UTC, bartjackbakker commented on manifests/database/postgresql.pp
> +  } elsif versioncmp($zabbix_version, '7.2') >= 0 {
This change is a good preparation for the LTS version 8.0.

2025-02-20 14:29 UTC, bartjackbakker commented on manifests/repo.pp
> +          undef   => versioncmp($zabbix_version, '7.2') ? {
This change is a good preparation for the LTS version 8.0.

2025-02-20 14:29 UTC, bartjackbakker commented on manifests/web.pp
> +    $zabbix_ui_dir = versioncmp($zabbix_version, '7.2') ? {
This change is a good preparation for the LTS version 8.0.

2025-02-20 14:29 UTC, bartjackbakker commented on spec/classes/database_postgresql_spec.rb
> +        path = if Puppet::Util::Package.versioncmp(zabbix_version, '7.2') >= 0
This change is a good preparation for the LTS version 8.0.

2025-02-20 14:29 UTC, bartjackbakker commented on spec/classes/repo_spec.rb
> +
This change is a good preparation for the LTS version 8.0.

2025-02-20 14:29 UTC, bartjackbakker commented on spec/support/acceptance/supported_versions.rb
> +  supported_versions = %w[5.0 6.0 7.0 7.2]
This change is a good preparation for the LTS version 8.0.

2025-02-27 12:24 UTC, Heidistein commented
Hi.
Yes, I agree with @bartjackbakker . Allthough you dont want to support normal releases (fair enough, I guess), all these changes are comming to 8.0. The moment 8.0 will be released the 7.2 tests can be changes to 8.0. In my opinion.

And, yes, this is in my own interest, because I'd like 7.2 deployed. :)

2025-06-05 13:52 UTC, d1nuc0m commented
@Safranil @Valantin any news on this? Zabbix 7.4 is planned for Q2 2025 and 8.0 LTS for Q4 2025 and the paths changes (that also affect the vhost) seem to be the same

2025-06-05 15:32 UTC, Valantin commented
need to fix CI again, after that I try to recheck it, but I think we can't run acceptance for non lts release

In spare time I try to refactor acceptance.

2026-09-10 07:38 UTC, d1nuc0m commented
Zabbix 7.2 is EOL as of 2025/12/31, probably sticking to LTS only is better

2026-09-10 07:38 UTC, closed without merging

2026-09-10 09:12 UTC, Safranil commented
> Zabbix 7.2 is EOL as of 2025/12/31, probably sticking to LTS only is better

Zabbix 7.4 and 8.0 (not yet released) follow the same repository pattern.

I can rework this MR to support Zabbix 8.0 instead of Zabbix 7.2.

2026-09-10 10:07 UTC, d1nuc0m commented
@Safranil that would be good, as 8.0 is in prerelease and is an LTS, reopen and ping me when it's ready

2026-09-14 08:38 UTC, Safranil commented
> @Safranil that would be good, as 8.0 is in prerelease and is an LTS, reopen and ping me when it's ready

@d1nuc0m I opened a new PR here: #1040.